<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="fddbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=61a6afb2-9dc8-4f45-97e3-a2b500ebed20.sqlserver.sequelizer.com;Initial Catalog=db61a6afb29dc84f4597e3a2b500ebed20;Persist Security Info=True;User ID=zpwsjtycbbjskoza" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db61a6afb29dc84f4597e3a2b500ebed20ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ggl" Member="ggls">
    <Type Name="ggl">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="refreshtoken" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="idlist" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_ggl" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.twt" Member="twts">
    <Type Name="twt">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="twtid" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="accesstoken" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="oauthtoken" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_twt" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.weather" Member="weathers">
    <Type Name="weather">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="icon" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.devices" Member="devices">
    <Type Name="device">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="useragent" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lastlogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UAmax" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="user_device" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.banners" Member="banners">
    <Type Name="banner">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="bannerid" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="user_banner" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="lastlogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lng" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="selection" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="user_ggl" Member="ggls" ThisKey="id" OtherKey="userid" Type="ggl" />
      <Association Name="user_twt" Member="twts" ThisKey="id" OtherKey="userid" Type="twt" />
      <Association Name="user_device" Member="devices" ThisKey="id" OtherKey="userid" Type="device" />
      <Association Name="user_banner" Member="banners" ThisKey="id" OtherKey="userid" Type="banner" />
      <Association Name="user_article" Member="articles" ThisKey="id" OtherKey="userid" Type="article" />
      <Association Name="user_comment" Member="comments" ThisKey="id" OtherKey="userid" Type="comment" />
    </Type>
  </Table>
  <Table Name="dbo.articles" Member="articles">
    <Type Name="article">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="heading" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="article" Member="article1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="article_comment" Member="comments" ThisKey="id" OtherKey="articleid" Type="comment" />
      <Association Name="user_article" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.comments" Member="comments">
    <Type Name="comment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comment" Member="comment1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="articleid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="article_comment" Member="article" ThisKey="articleid" OtherKey="id" Type="article" IsForeignKey="true" />
      <Association Name="user_comment" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
</Database>