<?xml version="1.0" encoding="utf-8"?><Database Name="fd1" Class="fddbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=U8001065-TPL-B\SQLEXPRESS;Initial Catalog=fd1;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="fd1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="lastlogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="user_ggl" Member="ggls" ThisKey="id" OtherKey="userid" Type="ggl" />
      <Association Name="user_twt" Member="twts" ThisKey="id" OtherKey="userid" Type="twt" />
    </Type>
  </Table>
  <Table Name="dbo.ggl" Member="ggls">
    <Type Name="ggl">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="refreshtoken" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="idlist" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_ggl" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.twt" Member="twts">
    <Type Name="twt">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="twtid" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="accesstoken" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="oauthtoken" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_twt" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
</Database>