<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="fddbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=61a6afb2-9dc8-4f45-97e3-a2b500ebed20.sqlserver.sequelizer.com;Persist Security Info=True;User ID=zpwsjtycbbjskoza" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataSourceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ggl" Member="ggls">
    <Type Name="ggl">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="refreshtoken" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="idlist" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_ggl" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.twt" Member="twts">
    <Type Name="twt">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="twtid" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="accesstoken" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="oauthtoken" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_twt" Member="user" ThisKey="userid" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="lastlogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lat" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lng" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="user_ggl" Member="ggls" ThisKey="id" OtherKey="userid" Type="ggl" />
      <Association Name="user_twt" Member="twts" ThisKey="id" OtherKey="userid" Type="twt" />
    </Type>
  </Table>
  <Table Name="dbo.weather" Member="weathers">
    <Type Name="weather">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="userid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="icon" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="hi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>